media: src/assets
content: 
  - name: posts
    label: posts
    type: collection
    path: src/content/blog
    fields:
      - { name: title, label: Title, type: string }
      - { name: pubDate, label: Publish Date, type: date }
      - { name: updatedDate, label: Last Update, type: date }
      - { name: description, label: Description, type: string, option: { maxlength: 160 } }
      - { name: category, label: Category, type: string }
      - { name: tags, label: Tags, type: select, option: { multiple: true, creatable: true }
      - { name: heroImage, label: Image, type: image }
      - { name: author, label: Author, type: string, default: "Paulo Henrique" }
      - { name: body, label: Body, type: rich-text }
      - { name: published, label: Published, type: boolean, default: false}
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc